feat: Add AST serialization and exporting support
distributed-lab/circom pull request #1
Opened 2024-03-07 14:36 UTC by YaCodesDevelopment

Added `--save_ast` flag. When passed, this should also output the `ast.json` file while compiling. The file includes an array of ASTs for all the files compiled.
This allows the use of that `ast.json` for further analysis of code in third-party libraries, unlocking the ability to create linters and other helper tools.

2024-03-07 14:41 UTC, Arvolear commented on parser/src/lib.rs
> +        let ast_list= serde_json::to_string(&ast_list).unwrap();
```suggestion
        let ast_list = serde_json::to_string(&ast_list).unwrap();
```

2024-03-07 19:37 UTC, Arvolear commented on circom/src/input_user.rs
> +        }
```suggestion
        match matches.is_present("save_ast"){
            true => 
               {
                   let path = matches.value_of("save_ast").unwrap();
                   if path != "" {
                        let path = Path::new(path);
                        if let Some(parent) = path.parent() {
                            std::fs::create_dir_all(parent).unwrap();
                        }
                        
                        if path.is_dir() {
                            PathBuf::from(path.join("ast.json").to_str().unwrap())
                        } else {
                            PathBuf::from(path.to_str().unwrap())
                        }
                    } else {
                        PathBuf::from("ast.json")
                    }
               }
               
            false => PathBuf::from("ast.json"),
        }
```

2024-03-13 12:40 UTC, Arvolear approved these changes
LGTM! (let's wait for the second approval)

2024-03-13 12:50 UTC, velykodnyi requested changes

2024-03-13 12:50 UTC, velykodnyi commented on circom/src/input_user.rs
> +    pub fn get_ast_path(matches: &ArgMatches) -> PathBuf {
Return Result and handle errors correctly(like you have in get_prime)

2024-03-13 12:50 UTC, velykodnyi commented on parser/src/lib.rs
> +        let ast_list = serde_json::to_string(&ast_list).unwrap();
Panics again

2024-03-13 19:09 UTC, velykodnyi approved these changes
LGTM

2024-03-13 19:30 UTC, merged